title: Easyfun
description: 英傑的程式之路

url: 
paginate_path: "https://easyfun0.github.io/Blog-astron/page:num/"
permalink: https://easyfun0.github.io/Blog-astron/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: Easyfun0
  twitter: 
  facebook: 
  email: mike9801215@gmail.com
  linkedin: 

# google_analytics: "UA-58263416-1"

disqus:
    shortname: EJ
