title: Easyfun
description: 英傑的程式之路

url: 
paginate_path: "Blog-astron/blog/page:num/"
permalink: Blog-astron/blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: https://easyfun0.github.io/Blog-astron/index.html
  - title: About
    url: https://easyfun0.github.io/Blog-astron/about
  - title: Contact
    url: https://easyfun0.github.io/Blog-astron/contact

social:
  github: Easyfun0
  twitter: 
  facebook: 
  email: mike9801215@gmail.com
  linkedin: 

# google_analytics: "UA-58263416-1"

disqus:
    shortname: EJ
